### ISSUE TITLE
Add "CrateDatabaseDialect" for resolving lack of JSON types used with "PostgreSqlDatabaseDialect"

### ISSUE THREAD

**Issue by amotl** [crate/kafka-connect-jdbc-crate-dialect#3]
Hi there,

coming from [1], we reported at https://github.com/crate/crate/issues/11347 about a problem with CrateDB where the `PostgreSqlDatabaseDialect` would use JSON data types, which are not yet available in CrateDB. We have been able to find out some details about the origin of the problem and extensively discussed what it would take to improve compatibility/interoperability between _Kafka Connect JDBC_ and _CrateDB_.

### Problem description
Kafka-connect-JDBC adds explicit `::json` casts for target columns of type `object` (exposed in `pg_catalog` as `json`). This currently breaks communication with CrateDB because `json` isn't available as type.

The reason for kafka-connect-JDBC doing that is that otherwise PostgreSQL errors when using prepared statements, see also http://sqlfiddle.com/#!17/7e29e/12, https://github.com/pgjdbc/pgjdbc/issues/265 and https://github.com/confluentinc/kafka-connect-jdbc/pull/875.

### Long-term solution
We settled the decision to implement a dedicated new JSON type in CrateDB instead of aliasing `::json` with `::object`, as suggested. However, this will probably take some time.

### Possible interim solution
In the meanwhile, we might well be looking into other possibilities to add improvements in this space.

We might want to add a `CrateDatabaseDialect`, which explicitly does not do the type casting added by https://github.com/confluentinc/kafka-connect-jdbc/pull/875. As we can see with #2, there might also be other details which might justify having a `CrateDatabaseDialect`.

I will be happy to hear about any thoughts on this.

With kind regards,
Andreas.

[1] https://community.crate.io/t/insert-a-column-as-json-using-kafka-jdbc-sink/663

/cc @mfussenegger, @seut, @mkleen, @jayeff, @proddata, @hammerhead, @dobe, @norosa, @quodt, @WalBeh, @rps-v, @ttrading

**Comment by mfussenegger** [comment]
> However, this will probably take some time.

Adding the `json` type/alias/whatever to CrateDB is less effort than the proposed intermediate solution. And it will happen within the 4.7 release.

I don't think maintaining a custom dialect is a viable solution given the current requirements - neither interim nor long term.

**Comment by amotl** [comment]
Hi Mathias,

thank you for your quick and clear response. Closing this.

With kind regards,
Andreas.
